### ISSUE TITLE
Segment server response 

### ISSUE THREAD

**Issue by ingnelson** [SkyLined/mTCPIPConnection#1]
Hello sir.

Is there a way to code on the server side to send the response via segment packet but not more than 2000 bytes for every packet till the whole data is send to the client ?

Example :
Whole data the server has to send back to the client is 5,000 bytes
Server send :
First packet 1800 bytes
Second packet 1500 bytes
Third packet 1700

If the answer is yes, could you create a  example for server please .

Is there a way? , I hope you answer

**Comment by SkyLined** [comment]
Hi,

No: this package is not designed to give you control over packet size. Also, your network may have an [MTU](https://en.wikipedia.org/wiki/Maximum_transmission_unit) that prevents you from sending packets of arbitrary size, so what you request may not even be possible.

Cheers,

SkyLined
